import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex items-center justify-center'>
          {/* Perhaps this link is also fuckign with the shifting */}
          <Link className='transition-colors hover:bg-slate-500 duration-500 py-2 z-10 w-full text-center bg-primary' href="/">
            scribbly
          </Link>
        </div>
        {children}
      </body>
    </html>
  )
}
